### ISSUE TITLE
Messages request

### ISSUE THREAD

**Issue by juliolitwin** [huynhsontung/Indirect#84] opened 2020-12-15 22:40 UTC
Hi,

- Have some way to accept the messages requests? Like some account is not following and send some direct?

Cheers.

**Comment by MarcAnt01** [comment] 2020-12-15 22:48
@juliolitwin I think that's a duplicate of https://github.com/huynhsontung/Indirect/issues/23

**Comment by juliolitwin** [comment] 2020-12-15 22:53
@MarcAnt01 Oh, I'm sorry, it really is a duplicate. 

One question, is the API completely independent of the GUI? I would like to be able to use the API in another type of application, such as receiving and sending messages as a chatbot. If possible, are there any possible tips?

**Comment by huynhsontung** [comment] 2020-12-16 09:46
@juliolitwin Please note that using Instagram API for making chatbot is against Instagram's policy. I strongly recommend NOT to use the API for this purpose.

That being said, yes the API is completely independent of the app. All endpoints related to push messaging reside in `InstagramAPI` directory and mostly in `Instagram.cs`, `Instagram.Direct.cs`, and `Instagram.MediaUpload.cs`. Note that these endpoints are (re)written to work specifically with the Windows platform. If you want a more general version of Instagram API, checkout [InstagramApiSharp](https://github.com/ramtinak/InstagramApiSharp) by [ramtinak](https://github.com/ramtinak/).

**Closed as completed** 2020-12-18 10:47 UTC
